forge "http://forge.puppetlabs.com"

mod 'camptocamp/systemd', '0.4.0'
mod 'garethr/docker', '5.3.0'
mod 'puppetlabs/apt', '2.2.2'
mod 'puppetlabs/inifile', '1.5.0'
mod 'puppetlabs/stdlib', '4.12.0'
mod 'ripienaar/classifier', '0.0.8'
mod 'choria/mcollective'
mod 'choria/mcollective_agent_filemgr'
mod 'choria/mcollective_agent_package'
mod 'choria/mcollective_agent_puppet'
mod 'choria/mcollective_agent_service'
mod 'choria/mcollective_choria'
mod 'choria/mcollective_util_actionpolicy'
mod 'choria/nats'
mod 'stahnma/epel', '1.2.2'
